// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: svc.infra.link/mq.proto

package link

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserEnterQuitAction int32

const (
	UserEnterQuitAction_Enter UserEnterQuitAction = 0
	UserEnterQuitAction_Quit  UserEnterQuitAction = 1
)

// Enum value maps for UserEnterQuitAction.
var (
	UserEnterQuitAction_name = map[int32]string{
		0: "Enter",
		1: "Quit",
	}
	UserEnterQuitAction_value = map[string]int32{
		"Enter": 0,
		"Quit":  1,
	}
)

func (x UserEnterQuitAction) Enum() *UserEnterQuitAction {
	p := new(UserEnterQuitAction)
	*p = x
	return p
}

func (x UserEnterQuitAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserEnterQuitAction) Descriptor() protoreflect.EnumDescriptor {
	return file_svc_infra_link_mq_proto_enumTypes[0].Descriptor()
}

func (UserEnterQuitAction) Type() protoreflect.EnumType {
	return &file_svc_infra_link_mq_proto_enumTypes[0]
}

func (x UserEnterQuitAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserEnterQuitAction.Descriptor instead.
func (UserEnterQuitAction) EnumDescriptor() ([]byte, []int) {
	return file_svc_infra_link_mq_proto_rawDescGZIP(), []int{0}
}

// 用户进出房间topic: topic.user.room.enter_quit
type UserEnterQuitRoomTopic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 房间ID
	RoomId     string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId     string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MerchantId string `protobuf:"bytes,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	// 当前直播间的在人数数量
	OnlineCount int64 `protobuf:"varint,4,opt,name=online_count,json=onlineCount,proto3" json:"online_count,omitempty"`
	// 主播ID
	StreamerId string              `protobuf:"bytes,5,opt,name=streamer_id,json=streamerId,proto3" json:"streamer_id,omitempty"`
	Action     UserEnterQuitAction `protobuf:"varint,255,opt,name=action,proto3,enum=svc.infra.link.UserEnterQuitAction" json:"action,omitempty"`
}

func (x *UserEnterQuitRoomTopic) Reset() {
	*x = UserEnterQuitRoomTopic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_infra_link_mq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserEnterQuitRoomTopic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEnterQuitRoomTopic) ProtoMessage() {}

func (x *UserEnterQuitRoomTopic) ProtoReflect() protoreflect.Message {
	mi := &file_svc_infra_link_mq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEnterQuitRoomTopic.ProtoReflect.Descriptor instead.
func (*UserEnterQuitRoomTopic) Descriptor() ([]byte, []int) {
	return file_svc_infra_link_mq_proto_rawDescGZIP(), []int{0}
}

func (x *UserEnterQuitRoomTopic) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *UserEnterQuitRoomTopic) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserEnterQuitRoomTopic) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *UserEnterQuitRoomTopic) GetOnlineCount() int64 {
	if x != nil {
		return x.OnlineCount
	}
	return 0
}

func (x *UserEnterQuitRoomTopic) GetStreamerId() string {
	if x != nil {
		return x.StreamerId
	}
	return ""
}

func (x *UserEnterQuitRoomTopic) GetAction() UserEnterQuitAction {
	if x != nil {
		return x.Action
	}
	return UserEnterQuitAction_Enter
}

var File_svc_infra_link_mq_proto protoreflect.FileDescriptor

var file_svc_infra_link_mq_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x76, 0x63, 0x2e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2e, 0x6c, 0x69, 0x6e, 0x6b,
	0x2f, 0x6d, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x73, 0x76, 0x63, 0x2e, 0x69,
	0x6e, 0x66, 0x72, 0x61, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x22, 0xed, 0x01, 0x0a, 0x16, 0x55, 0x73,
	0x65, 0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x51, 0x75, 0x69, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x54,
	0x6f, 0x70, 0x69, 0x63, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x72,
	0x63, 0x68, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0xff, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x73,
	0x76, 0x63, 0x2e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x51, 0x75, 0x69, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2a, 0x2a, 0x0a, 0x13, 0x55, 0x73, 0x65,
	0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x51, 0x75, 0x69, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x09, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x51,
	0x75, 0x69, 0x74, 0x10, 0x01, 0x42, 0x17, 0x5a, 0x15, 0x2e, 0x2f, 0x73, 0x76, 0x63, 0x2e, 0x69,
	0x6e, 0x66, 0x72, 0x61, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x3b, 0x6c, 0x69, 0x6e, 0x6b, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_svc_infra_link_mq_proto_rawDescOnce sync.Once
	file_svc_infra_link_mq_proto_rawDescData = file_svc_infra_link_mq_proto_rawDesc
)

func file_svc_infra_link_mq_proto_rawDescGZIP() []byte {
	file_svc_infra_link_mq_proto_rawDescOnce.Do(func() {
		file_svc_infra_link_mq_proto_rawDescData = protoimpl.X.CompressGZIP(file_svc_infra_link_mq_proto_rawDescData)
	})
	return file_svc_infra_link_mq_proto_rawDescData
}

var file_svc_infra_link_mq_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_svc_infra_link_mq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_svc_infra_link_mq_proto_goTypes = []interface{}{
	(UserEnterQuitAction)(0),       // 0: svc.infra.link.UserEnterQuitAction
	(*UserEnterQuitRoomTopic)(nil), // 1: svc.infra.link.UserEnterQuitRoomTopic
}
var file_svc_infra_link_mq_proto_depIdxs = []int32{
	0, // 0: svc.infra.link.UserEnterQuitRoomTopic.action:type_name -> svc.infra.link.UserEnterQuitAction
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_svc_infra_link_mq_proto_init() }
func file_svc_infra_link_mq_proto_init() {
	if File_svc_infra_link_mq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_svc_infra_link_mq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserEnterQuitRoomTopic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_svc_infra_link_mq_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_svc_infra_link_mq_proto_goTypes,
		DependencyIndexes: file_svc_infra_link_mq_proto_depIdxs,
		EnumInfos:         file_svc_infra_link_mq_proto_enumTypes,
		MessageInfos:      file_svc_infra_link_mq_proto_msgTypes,
	}.Build()
	File_svc_infra_link_mq_proto = out.File
	file_svc_infra_link_mq_proto_rawDesc = nil
	file_svc_infra_link_mq_proto_goTypes = nil
	file_svc_infra_link_mq_proto_depIdxs = nil
}
