// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: svc.web.streamer/streamer.proto

package streamer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_svc_web_streamer_streamer_proto protoreflect.FileDescriptor

var file_svc_web_streamer_streamer_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x73, 0x76, 0x63, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x65, 0x72, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x10, 0x73, 0x76, 0x63, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x65, 0x72, 0x32, 0x0a, 0x0a, 0x08, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x72, 0x42,
	0x1d, 0x5a, 0x1b, 0x2e, 0x2f, 0x73, 0x76, 0x63, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x65, 0x72, 0x3b, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_svc_web_streamer_streamer_proto_goTypes = []any{}
var file_svc_web_streamer_streamer_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_svc_web_streamer_streamer_proto_init() }
func file_svc_web_streamer_streamer_proto_init() {
	if File_svc_web_streamer_streamer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_svc_web_streamer_streamer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_svc_web_streamer_streamer_proto_goTypes,
		DependencyIndexes: file_svc_web_streamer_streamer_proto_depIdxs,
	}.Build()
	File_svc_web_streamer_streamer_proto = out.File
	file_svc_web_streamer_streamer_proto_rawDesc = nil
	file_svc_web_streamer_streamer_proto_goTypes = nil
	file_svc_web_streamer_streamer_proto_depIdxs = nil
}
