// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: svc.infra.setting/setting.proto

package setting

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Setting service

func NewSettingEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Setting service

type SettingService interface {
}

type settingService struct {
	c    client.Client
	name string
}

func NewSettingService(name string, c client.Client) SettingService {
	return &settingService{
		c:    c,
		name: name,
	}
}

// Server API for Setting service

type SettingHandler interface {
}

func RegisterSettingHandler(s server.Server, hdlr SettingHandler, opts ...server.HandlerOption) error {
	type setting interface {
	}
	type Setting struct {
		setting
	}
	h := &settingHandler{hdlr}
	return s.Handle(s.NewHandler(&Setting{h}, opts...))
}

type settingHandler struct {
	SettingHandler
}
