// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: svc.biz.room/live.proto

package room

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Live service

func NewLiveEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Live service

type LiveService interface {
	// 查询直播间信息
	GetLiveInfo(ctx context.Context, in *GetLiveInfoReq, opts ...client.CallOption) (*GetLiveInfoResp, error)
	// 批量获取直播间信息
	MGetLiveInfo(ctx context.Context, in *MGetLiveInfoReq, opts ...client.CallOption) (*MGetLiveInfoResp, error)
	// 获取在播直播间列表
	ListLiveInfo(ctx context.Context, in *ListLiveInfoReq, opts ...client.CallOption) (*ListLiveInfoResp, error)
}

type liveService struct {
	c    client.Client
	name string
}

func NewLiveService(name string, c client.Client) LiveService {
	return &liveService{
		c:    c,
		name: name,
	}
}

func (c *liveService) GetLiveInfo(ctx context.Context, in *GetLiveInfoReq, opts ...client.CallOption) (*GetLiveInfoResp, error) {
	req := c.c.NewRequest(c.name, "Live.GetLiveInfo", in)
	out := new(GetLiveInfoResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liveService) MGetLiveInfo(ctx context.Context, in *MGetLiveInfoReq, opts ...client.CallOption) (*MGetLiveInfoResp, error) {
	req := c.c.NewRequest(c.name, "Live.MGetLiveInfo", in)
	out := new(MGetLiveInfoResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liveService) ListLiveInfo(ctx context.Context, in *ListLiveInfoReq, opts ...client.CallOption) (*ListLiveInfoResp, error) {
	req := c.c.NewRequest(c.name, "Live.ListLiveInfo", in)
	out := new(ListLiveInfoResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Live service

type LiveHandler interface {
	// 查询直播间信息
	GetLiveInfo(context.Context, *GetLiveInfoReq, *GetLiveInfoResp) error
	// 批量获取直播间信息
	MGetLiveInfo(context.Context, *MGetLiveInfoReq, *MGetLiveInfoResp) error
	// 获取在播直播间列表
	ListLiveInfo(context.Context, *ListLiveInfoReq, *ListLiveInfoResp) error
}

func RegisterLiveHandler(s server.Server, hdlr LiveHandler, opts ...server.HandlerOption) error {
	type live interface {
		GetLiveInfo(ctx context.Context, in *GetLiveInfoReq, out *GetLiveInfoResp) error
		MGetLiveInfo(ctx context.Context, in *MGetLiveInfoReq, out *MGetLiveInfoResp) error
		ListLiveInfo(ctx context.Context, in *ListLiveInfoReq, out *ListLiveInfoResp) error
	}
	type Live struct {
		live
	}
	h := &liveHandler{hdlr}
	return s.Handle(s.NewHandler(&Live{h}, opts...))
}

type liveHandler struct {
	LiveHandler
}

func (h *liveHandler) GetLiveInfo(ctx context.Context, in *GetLiveInfoReq, out *GetLiveInfoResp) error {
	return h.LiveHandler.GetLiveInfo(ctx, in, out)
}

func (h *liveHandler) MGetLiveInfo(ctx context.Context, in *MGetLiveInfoReq, out *MGetLiveInfoResp) error {
	return h.LiveHandler.MGetLiveInfo(ctx, in, out)
}

func (h *liveHandler) ListLiveInfo(ctx context.Context, in *ListLiveInfoReq, out *ListLiveInfoResp) error {
	return h.LiveHandler.ListLiveInfo(ctx, in, out)
}
