// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: svc.biz.room/live.proto

package room

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LiveInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LiveId     string                 `protobuf:"bytes,1,opt,name=live_id,json=liveId,proto3" json:"live_id,omitempty"`             // id
	StreamerId string                 `protobuf:"bytes,2,opt,name=streamer_id,json=streamerId,proto3" json:"streamer_id,omitempty"` // 主播id
	RoomId     string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`             // 房间id
	CategoryId string                 `protobuf:"bytes,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"` // 分类id
	StartAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`          // 开播时间
	EndAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`                // 结束时间
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,255,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`  // 创建时间
	UpdatedAt  *timestamppb.Timestamp `protobuf:"bytes,256,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`  // 更新时间
}

func (x *LiveInfo) Reset() {
	*x = LiveInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_biz_room_live_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveInfo) ProtoMessage() {}

func (x *LiveInfo) ProtoReflect() protoreflect.Message {
	mi := &file_svc_biz_room_live_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveInfo.ProtoReflect.Descriptor instead.
func (*LiveInfo) Descriptor() ([]byte, []int) {
	return file_svc_biz_room_live_proto_rawDescGZIP(), []int{0}
}

func (x *LiveInfo) GetLiveId() string {
	if x != nil {
		return x.LiveId
	}
	return ""
}

func (x *LiveInfo) GetStreamerId() string {
	if x != nil {
		return x.StreamerId
	}
	return ""
}

func (x *LiveInfo) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *LiveInfo) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *LiveInfo) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *LiveInfo) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

func (x *LiveInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *LiveInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetLiveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LiveId string `protobuf:"bytes,1,opt,name=live_id,json=liveId,proto3" json:"live_id,omitempty"` // 直播id
}

func (x *GetLiveReq) Reset() {
	*x = GetLiveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_biz_room_live_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLiveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLiveReq) ProtoMessage() {}

func (x *GetLiveReq) ProtoReflect() protoreflect.Message {
	mi := &file_svc_biz_room_live_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLiveReq.ProtoReflect.Descriptor instead.
func (*GetLiveReq) Descriptor() ([]byte, []int) {
	return file_svc_biz_room_live_proto_rawDescGZIP(), []int{1}
}

func (x *GetLiveReq) GetLiveId() string {
	if x != nil {
		return x.LiveId
	}
	return ""
}

type GetLiveResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Live *LiveInfo `protobuf:"bytes,1,opt,name=live,proto3" json:"live,omitempty"` // 直播信息
}

func (x *GetLiveResp) Reset() {
	*x = GetLiveResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_biz_room_live_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLiveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLiveResp) ProtoMessage() {}

func (x *GetLiveResp) ProtoReflect() protoreflect.Message {
	mi := &file_svc_biz_room_live_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLiveResp.ProtoReflect.Descriptor instead.
func (*GetLiveResp) Descriptor() ([]byte, []int) {
	return file_svc_biz_room_live_proto_rawDescGZIP(), []int{2}
}

func (x *GetLiveResp) GetLive() *LiveInfo {
	if x != nil {
		return x.Live
	}
	return nil
}

type MGetLiveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LiveIds []string `protobuf:"bytes,1,rep,name=live_ids,json=liveIds,proto3" json:"live_ids,omitempty"` // 直播id列表
}

func (x *MGetLiveReq) Reset() {
	*x = MGetLiveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_biz_room_live_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MGetLiveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MGetLiveReq) ProtoMessage() {}

func (x *MGetLiveReq) ProtoReflect() protoreflect.Message {
	mi := &file_svc_biz_room_live_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MGetLiveReq.ProtoReflect.Descriptor instead.
func (*MGetLiveReq) Descriptor() ([]byte, []int) {
	return file_svc_biz_room_live_proto_rawDescGZIP(), []int{3}
}

func (x *MGetLiveReq) GetLiveIds() []string {
	if x != nil {
		return x.LiveIds
	}
	return nil
}

type MGetLiveResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items map[string]*LiveInfo `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 直播信息
}

func (x *MGetLiveResp) Reset() {
	*x = MGetLiveResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_biz_room_live_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MGetLiveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MGetLiveResp) ProtoMessage() {}

func (x *MGetLiveResp) ProtoReflect() protoreflect.Message {
	mi := &file_svc_biz_room_live_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MGetLiveResp.ProtoReflect.Descriptor instead.
func (*MGetLiveResp) Descriptor() ([]byte, []int) {
	return file_svc_biz_room_live_proto_rawDescGZIP(), []int{4}
}

func (x *MGetLiveResp) GetItems() map[string]*LiveInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListLiveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page       int32  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                              // 页数
	Limit      int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                            // 条数
	StreamerId string `protobuf:"bytes,3,opt,name=streamer_id,json=streamerId,proto3" json:"streamer_id,omitempty"` // 主播id
}

func (x *ListLiveReq) Reset() {
	*x = ListLiveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_biz_room_live_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLiveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLiveReq) ProtoMessage() {}

func (x *ListLiveReq) ProtoReflect() protoreflect.Message {
	mi := &file_svc_biz_room_live_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLiveReq.ProtoReflect.Descriptor instead.
func (*ListLiveReq) Descriptor() ([]byte, []int) {
	return file_svc_biz_room_live_proto_rawDescGZIP(), []int{5}
}

func (x *ListLiveReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLiveReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListLiveReq) GetStreamerId() string {
	if x != nil {
		return x.StreamerId
	}
	return ""
}

type ListLiveResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*LiveInfo `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // 直播信息
}

func (x *ListLiveResp) Reset() {
	*x = ListLiveResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_biz_room_live_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLiveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLiveResp) ProtoMessage() {}

func (x *ListLiveResp) ProtoReflect() protoreflect.Message {
	mi := &file_svc_biz_room_live_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLiveResp.ProtoReflect.Descriptor instead.
func (*ListLiveResp) Descriptor() ([]byte, []int) {
	return file_svc_biz_room_live_proto_rawDescGZIP(), []int{6}
}

func (x *ListLiveResp) GetItems() []*LiveInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

type StatLiveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartAtBeigin *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_at_beigin,json=startAtBeigin,proto3" json:"start_at_beigin,omitempty"`
	StartAtEnd    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_at_end,json=startAtEnd,proto3" json:"start_at_end,omitempty"`
}

func (x *StatLiveReq) Reset() {
	*x = StatLiveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_biz_room_live_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatLiveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatLiveReq) ProtoMessage() {}

func (x *StatLiveReq) ProtoReflect() protoreflect.Message {
	mi := &file_svc_biz_room_live_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatLiveReq.ProtoReflect.Descriptor instead.
func (*StatLiveReq) Descriptor() ([]byte, []int) {
	return file_svc_biz_room_live_proto_rawDescGZIP(), []int{7}
}

func (x *StatLiveReq) GetStartAtBeigin() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAtBeigin
	}
	return nil
}

func (x *StatLiveReq) GetStartAtEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAtEnd
	}
	return nil
}

type StatLiveResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count    int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`       // 直播次数
	Duration int64 `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"` // 直播时长
}

func (x *StatLiveResp) Reset() {
	*x = StatLiveResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_biz_room_live_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatLiveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatLiveResp) ProtoMessage() {}

func (x *StatLiveResp) ProtoReflect() protoreflect.Message {
	mi := &file_svc_biz_room_live_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatLiveResp.ProtoReflect.Descriptor instead.
func (*StatLiveResp) Descriptor() ([]byte, []int) {
	return file_svc_biz_room_live_proto_rawDescGZIP(), []int{8}
}

func (x *StatLiveResp) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *StatLiveResp) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

var File_svc_biz_room_live_proto protoreflect.FileDescriptor

var file_svc_biz_room_live_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x76, 0x63, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2f, 0x6c,
	0x69, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x76, 0x63, 0x2e, 0x62,
	0x69, 0x7a, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe0, 0x02, 0x0a, 0x08, 0x4c, 0x69, 0x76,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x69, 0x76, 0x65, 0x49, 0x64, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x08, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74,
	0x12, 0x31, 0x0a, 0x06, 0x65, 0x6e, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x05, 0x65, 0x6e,
	0x64, 0x41, 0x74, 0x12, 0x3a, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0xff, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x3a, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x80, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x25, 0x0a, 0x0a, 0x47,
	0x65, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x69, 0x76,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x69, 0x76, 0x65,
	0x49, 0x64, 0x22, 0x39, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x2a, 0x0a, 0x04, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x4c,
	0x69, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6c, 0x69, 0x76, 0x65, 0x22, 0x28, 0x0a,
	0x0b, 0x4d, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08,
	0x6c, 0x69, 0x76, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x6c, 0x69, 0x76, 0x65, 0x49, 0x64, 0x73, 0x22, 0x9d, 0x01, 0x0a, 0x0c, 0x4d, 0x47, 0x65, 0x74,
	0x4c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3b, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x62, 0x69,
	0x7a, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x4d, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x50, 0x0a, 0x0a, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x72,
	0x6f, 0x6f, 0x6d, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x58, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x4c,
	0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x3c, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x2c, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e,
	0x4c, 0x69, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22,
	0x8f, 0x01, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x42, 0x0a, 0x0f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x61, 0x74, 0x5f, 0x62, 0x65, 0x69, 0x67,
	0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x0d, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x42, 0x65, 0x69,
	0x67, 0x69, 0x6e, 0x12, 0x3c, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x61, 0x74, 0x5f,
	0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x45, 0x6e,
	0x64, 0x22, 0x40, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x32, 0x8f, 0x02, 0x0a, 0x04, 0x4c, 0x69, 0x76, 0x65, 0x12, 0x3e, 0x0a, 0x07,
	0x47, 0x65, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x12, 0x18, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x62, 0x69,
	0x7a, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x65,
	0x71, 0x1a, 0x19, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x72, 0x6f, 0x6f, 0x6d,
	0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x41, 0x0a, 0x08,
	0x4d, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x12, 0x19, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x62,
	0x69, 0x7a, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x4d, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x76, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x72, 0x6f,
	0x6f, 0x6d, 0x2e, 0x4d, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x41, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x12, 0x19, 0x2e, 0x73, 0x76,
	0x63, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4c,
	0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x62, 0x69, 0x7a,
	0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x41, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x12, 0x19,
	0x2e, 0x73, 0x76, 0x63, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x73, 0x76, 0x63, 0x2e,
	0x62, 0x69, 0x7a, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x4c, 0x69, 0x76,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x15, 0x5a, 0x13, 0x2e, 0x2f, 0x73, 0x76, 0x63, 0x2e, 0x62,
	0x69, 0x7a, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x3b, 0x72, 0x6f, 0x6f, 0x6d, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_svc_biz_room_live_proto_rawDescOnce sync.Once
	file_svc_biz_room_live_proto_rawDescData = file_svc_biz_room_live_proto_rawDesc
)

func file_svc_biz_room_live_proto_rawDescGZIP() []byte {
	file_svc_biz_room_live_proto_rawDescOnce.Do(func() {
		file_svc_biz_room_live_proto_rawDescData = protoimpl.X.CompressGZIP(file_svc_biz_room_live_proto_rawDescData)
	})
	return file_svc_biz_room_live_proto_rawDescData
}

var file_svc_biz_room_live_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_svc_biz_room_live_proto_goTypes = []any{
	(*LiveInfo)(nil),              // 0: svc.biz.room.LiveInfo
	(*GetLiveReq)(nil),            // 1: svc.biz.room.GetLiveReq
	(*GetLiveResp)(nil),           // 2: svc.biz.room.GetLiveResp
	(*MGetLiveReq)(nil),           // 3: svc.biz.room.MGetLiveReq
	(*MGetLiveResp)(nil),          // 4: svc.biz.room.MGetLiveResp
	(*ListLiveReq)(nil),           // 5: svc.biz.room.ListLiveReq
	(*ListLiveResp)(nil),          // 6: svc.biz.room.ListLiveResp
	(*StatLiveReq)(nil),           // 7: svc.biz.room.StatLiveReq
	(*StatLiveResp)(nil),          // 8: svc.biz.room.StatLiveResp
	nil,                           // 9: svc.biz.room.MGetLiveResp.ItemsEntry
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_svc_biz_room_live_proto_depIdxs = []int32{
	10, // 0: svc.biz.room.LiveInfo.start_at:type_name -> google.protobuf.Timestamp
	10, // 1: svc.biz.room.LiveInfo.end_at:type_name -> google.protobuf.Timestamp
	10, // 2: svc.biz.room.LiveInfo.created_at:type_name -> google.protobuf.Timestamp
	10, // 3: svc.biz.room.LiveInfo.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: svc.biz.room.GetLiveResp.live:type_name -> svc.biz.room.LiveInfo
	9,  // 5: svc.biz.room.MGetLiveResp.items:type_name -> svc.biz.room.MGetLiveResp.ItemsEntry
	0,  // 6: svc.biz.room.ListLiveResp.items:type_name -> svc.biz.room.LiveInfo
	10, // 7: svc.biz.room.StatLiveReq.start_at_beigin:type_name -> google.protobuf.Timestamp
	10, // 8: svc.biz.room.StatLiveReq.start_at_end:type_name -> google.protobuf.Timestamp
	0,  // 9: svc.biz.room.MGetLiveResp.ItemsEntry.value:type_name -> svc.biz.room.LiveInfo
	1,  // 10: svc.biz.room.Live.GetLive:input_type -> svc.biz.room.GetLiveReq
	3,  // 11: svc.biz.room.Live.MGetLive:input_type -> svc.biz.room.MGetLiveReq
	5,  // 12: svc.biz.room.Live.ListLive:input_type -> svc.biz.room.ListLiveReq
	7,  // 13: svc.biz.room.Live.StatLive:input_type -> svc.biz.room.StatLiveReq
	2,  // 14: svc.biz.room.Live.GetLive:output_type -> svc.biz.room.GetLiveResp
	4,  // 15: svc.biz.room.Live.MGetLive:output_type -> svc.biz.room.MGetLiveResp
	6,  // 16: svc.biz.room.Live.ListLive:output_type -> svc.biz.room.ListLiveResp
	8,  // 17: svc.biz.room.Live.StatLive:output_type -> svc.biz.room.StatLiveResp
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_svc_biz_room_live_proto_init() }
func file_svc_biz_room_live_proto_init() {
	if File_svc_biz_room_live_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_svc_biz_room_live_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*LiveInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_biz_room_live_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetLiveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_biz_room_live_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetLiveResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_biz_room_live_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*MGetLiveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_biz_room_live_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*MGetLiveResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_biz_room_live_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ListLiveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_biz_room_live_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ListLiveResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_biz_room_live_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*StatLiveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_biz_room_live_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*StatLiveResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_svc_biz_room_live_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_svc_biz_room_live_proto_goTypes,
		DependencyIndexes: file_svc_biz_room_live_proto_depIdxs,
		MessageInfos:      file_svc_biz_room_live_proto_msgTypes,
	}.Build()
	File_svc_biz_room_live_proto = out.File
	file_svc_biz_room_live_proto_rawDesc = nil
	file_svc_biz_room_live_proto_goTypes = nil
	file_svc_biz_room_live_proto_depIdxs = nil
}
