// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: svc.web.dashboard/dashboard.proto

package dashboard

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "go-micro.dev/v5/client"
	server "go-micro.dev/v5/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Dashboard service

type DashboardService interface {
}

type dashboardService struct {
	c    client.Client
	name string
}

func NewDashboardService(name string, c client.Client) DashboardService {
	return &dashboardService{
		c:    c,
		name: name,
	}
}

// Server API for Dashboard service

type DashboardHandler interface {
}

func RegisterDashboardHandler(s server.Server, hdlr DashboardHandler, opts ...server.HandlerOption) error {
	type dashboard interface {
	}
	type Dashboard struct {
		dashboard
	}
	h := &dashboardHandler{hdlr}
	return s.Handle(s.NewHandler(&Dashboard{h}, opts...))
}

type dashboardHandler struct {
	DashboardHandler
}
