// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: svc.biz.rank/streamer_viewer_rank.proto

package rank

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for StreamerViewerRank service

func NewStreamerViewerRankEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for StreamerViewerRank service

type StreamerViewerRankService interface {
	// 获取主播在线的排行榜成员
	GetStreamerViewerOnlineMember(ctx context.Context, in *GetStreamerViewerOnlineMemberReq, opts ...client.CallOption) (*GetStreamerViewerRankResp, error)
	// 获取给主播贡献礼物的排行榜成员
	GetStreamerViewerGiftMember(ctx context.Context, in *GetStreamerViewerGiftMemberReq, opts ...client.CallOption) (*GetStreamerViewerRankResp, error)
	// 获取给主播贡献魅力值的排行榜成员
	GetStreamerViewerGlamourMember(ctx context.Context, in *GetStreamerViewerGlamourMemberReq, opts ...client.CallOption) (*GetStreamerViewerRankResp, error)
}

type streamerViewerRankService struct {
	c    client.Client
	name string
}

func NewStreamerViewerRankService(name string, c client.Client) StreamerViewerRankService {
	return &streamerViewerRankService{
		c:    c,
		name: name,
	}
}

func (c *streamerViewerRankService) GetStreamerViewerOnlineMember(ctx context.Context, in *GetStreamerViewerOnlineMemberReq, opts ...client.CallOption) (*GetStreamerViewerRankResp, error) {
	req := c.c.NewRequest(c.name, "StreamerViewerRank.GetStreamerViewerOnlineMember", in)
	out := new(GetStreamerViewerRankResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamerViewerRankService) GetStreamerViewerGiftMember(ctx context.Context, in *GetStreamerViewerGiftMemberReq, opts ...client.CallOption) (*GetStreamerViewerRankResp, error) {
	req := c.c.NewRequest(c.name, "StreamerViewerRank.GetStreamerViewerGiftMember", in)
	out := new(GetStreamerViewerRankResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamerViewerRankService) GetStreamerViewerGlamourMember(ctx context.Context, in *GetStreamerViewerGlamourMemberReq, opts ...client.CallOption) (*GetStreamerViewerRankResp, error) {
	req := c.c.NewRequest(c.name, "StreamerViewerRank.GetStreamerViewerGlamourMember", in)
	out := new(GetStreamerViewerRankResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StreamerViewerRank service

type StreamerViewerRankHandler interface {
	// 获取主播在线的排行榜成员
	GetStreamerViewerOnlineMember(context.Context, *GetStreamerViewerOnlineMemberReq, *GetStreamerViewerRankResp) error
	// 获取给主播贡献礼物的排行榜成员
	GetStreamerViewerGiftMember(context.Context, *GetStreamerViewerGiftMemberReq, *GetStreamerViewerRankResp) error
	// 获取给主播贡献魅力值的排行榜成员
	GetStreamerViewerGlamourMember(context.Context, *GetStreamerViewerGlamourMemberReq, *GetStreamerViewerRankResp) error
}

func RegisterStreamerViewerRankHandler(s server.Server, hdlr StreamerViewerRankHandler, opts ...server.HandlerOption) error {
	type streamerViewerRank interface {
		GetStreamerViewerOnlineMember(ctx context.Context, in *GetStreamerViewerOnlineMemberReq, out *GetStreamerViewerRankResp) error
		GetStreamerViewerGiftMember(ctx context.Context, in *GetStreamerViewerGiftMemberReq, out *GetStreamerViewerRankResp) error
		GetStreamerViewerGlamourMember(ctx context.Context, in *GetStreamerViewerGlamourMemberReq, out *GetStreamerViewerRankResp) error
	}
	type StreamerViewerRank struct {
		streamerViewerRank
	}
	h := &streamerViewerRankHandler{hdlr}
	return s.Handle(s.NewHandler(&StreamerViewerRank{h}, opts...))
}

type streamerViewerRankHandler struct {
	StreamerViewerRankHandler
}

func (h *streamerViewerRankHandler) GetStreamerViewerOnlineMember(ctx context.Context, in *GetStreamerViewerOnlineMemberReq, out *GetStreamerViewerRankResp) error {
	return h.StreamerViewerRankHandler.GetStreamerViewerOnlineMember(ctx, in, out)
}

func (h *streamerViewerRankHandler) GetStreamerViewerGiftMember(ctx context.Context, in *GetStreamerViewerGiftMemberReq, out *GetStreamerViewerRankResp) error {
	return h.StreamerViewerRankHandler.GetStreamerViewerGiftMember(ctx, in, out)
}

func (h *streamerViewerRankHandler) GetStreamerViewerGlamourMember(ctx context.Context, in *GetStreamerViewerGlamourMemberReq, out *GetStreamerViewerRankResp) error {
	return h.StreamerViewerRankHandler.GetStreamerViewerGlamourMember(ctx, in, out)
}
