// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.2
// source: svc.web.viewer/viewer.proto

package viewer

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

// ViewerClient is the client API for Viewer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ViewerClient interface {
}

type viewerClient struct {
	cc grpc.ClientConnInterface
}

func NewViewerClient(cc grpc.ClientConnInterface) ViewerClient {
	return &viewerClient{cc}
}

// ViewerServer is the server API for Viewer service.
// All implementations must embed UnimplementedViewerServer
// for forward compatibility
type ViewerServer interface {
	mustEmbedUnimplementedViewerServer()
}

// UnimplementedViewerServer must be embedded to have forward compatible implementations.
type UnimplementedViewerServer struct {
}

func (UnimplementedViewerServer) mustEmbedUnimplementedViewerServer() {}

// UnsafeViewerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ViewerServer will
// result in compilation errors.
type UnsafeViewerServer interface {
	mustEmbedUnimplementedViewerServer()
}

func RegisterViewerServer(s grpc.ServiceRegistrar, srv ViewerServer) {
	s.RegisterService(&Viewer_ServiceDesc, srv)
}

// Viewer_ServiceDesc is the grpc.ServiceDesc for Viewer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Viewer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "svc.web.viewer.Viewer",
	HandlerType: (*ViewerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "svc.web.viewer/viewer.proto",
}
